swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
  - name: "community"
    description: "Operations about user"
    externalDocs:
      description: "Find out more about our store"
      url: "http://swagger.io"
schemes:
  - "https"
  - "http"
paths:
  /community/regi:
    post:
      tags:
        - "community"
      summary: "Create"
      description: "글 작성."
      operationId: "Create content"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            $ref: "#/definitions/community"
      responses:
        default:
          description: "successful operation"
  /community/list:
    get:
      tags:
        - "community"
      summary: "list"
      description: "글 목록 보기"
      operationId: "community list"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "community_code"
          in: "query"
          description: "커뮤니티 코드"
          required: false
          type: "string"
        - name: "keyword"
          in: "query"
          description: "검색어"
          required: false
          type: "string"
        - name: "page_no"
          in: "query"
          description: "page Number"
          required: true
          type: "integer"
      responses:
        default:
          description: "successful operation"

  /community/update:
    put:
      tags:
        - "community"
      summary: "update community"
      description: "글 정보 업데이트"
      operationId: "update content"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "update object"
          required: true
          schema:
            $ref: "#/definitions/community_update"
      responses:
        default:
          description: "successful operation"

  /community/detail/{community_no}:
    get:
      tags:
        - "community"
      summary: "view detail"
      description: "선택된 글 상세보기"
      operationId: "view Detail"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: path
          name: "community_no"
          description: "view object"
          required: true
      responses:
        default:
          description: "successful operation"

  /community/delete/{community_no}:
    delete:
      tags:
        - "community"
      summary: "delete"
      description: "선택된 글 삭제"
      operationId: "delete"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: path
          name: "community_no"
          description: "view object"
          required: true
      responses:
        default:
          description: "successful operation"

  /community/listcount:
    get:
      tags:
        - "community"
      summary: "listcount"
      description: "글 목록 개수 보기"
      operationId: "community list count"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "community_code"
          in: "query"
          description: "community list count"
          required: false
          type: "string"
        - name: "keyword"
          in: "query"
          description: "검색어"
          required: false
          type: "string"
      responses:
        default:
          description: "successful operation"

  /community/comment/write:
    post:
      tags:
        - "community_comment"
      summary: "write community_comment"
      description: "write community_comment"
      operationId: "write community_comment"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "write community_comment"
          required: true
          schema:
            $ref: "#/definitions/community_comment_write"
      responses:
        default:
          description: "successful operation"

  /community/comment/update:
    put:
      tags:
        - "community_comment"
      summary: "Update community_comment"
      description: "Update community_comment"
      operationId: "Update community_comment"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Update community_comment"
          required: true
          schema:
            $ref: "#/definitions/community_comment_update"
      responses:
        default:
          description: "successful operation"

  /community/comment/delete/{no}:
    delete:
      tags:
        - "community_comment"
      summary: "Delete by community_comment"
      description: "For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors"
      operationId: "delete community_comment"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "path"
          name: "no"
          description: "no of the notice that needs to be deleted"
          required: true
          type: "integer"
      responses:
        default:
          description: "successful operation"

  /community/comment/list:
    get:
      tags:
        - "community_comment"
      summary: "list"
      description: "댓글 목록 보기"
      operationId: "community comment list"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "community_no"
          in: "query"
          description: "community comment list"
          required: false
          type: "integer"
      responses:
        default:
          description: "successful operation"

securityDefinitions:
  jwt:
    type: apiKey
    name: "Authorization"
    in: "header"

definitions:
  community:
    type: "object"
    properties:
      community_title:
        type: "string"
      community_author:
        type: "string"
      community_content:
        type: "string"
      community_code:
        type: "string"
      community_user_id:
        type: "string"
    xml:
      name: "community"
  community_search:
    type: "object"
    properties:
      community_title:
        type: "string"
      community_author:
        type: "string"
    xml:
      name: "community_search"
  community_update:
    type: "object"
    properties:
      community_title:
        type: "string"
      community_content:
        type: "string"
      community_no:
        type: "integer"
        format: "int64"
    xml:
      name: "community_update"

  community_comment_write:
    type: "object"
    properties:
      comment_user_nickName:
        type: "string"
      community_no:
        type: "integer"
      comment_text:
        type: "string"
      comment_user_id:
        type: "string"
    xml:
      name: "community_comment_write"

  community_comment_update:
    type: "object"
    properties:
      comment_no:
        type: "integer"
      comment_text:
        type: "string"
    xml:
      name: "community_comment_update"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
